stages:
  - test
  - publish
  - push

# Templates
.docker_base: &docker_base
  image: docker:latest
  before_script:
    - apk add --update make
    - apk add --update docker-compose
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2

.publish_base: &publish_base
  stage: publish
  image: python:3.9-slim-buster
  before_script:
    - cd fides_cli/
    - pip install twine
    - python setup.py sdist

# Jobs
test-all:
  stage: test
  <<: *docker_base
  script:
    - make server-test
    - make cli-check-all
  only:
    refs:
      - merge_requests

push-server:
  stage: push
  <<: *docker_base
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make server-push
  only:
    refs:
      - master

push-cli:
  stage: push
  <<: *docker_base
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make cli-push
  only:
    refs:
      - master

test-publish:
  <<: *publish_base
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: "$TEST_PYPI_TOKEN"
  script:
    - twine upload --repository testpypi dist/*
  when: manual

publish:
  <<: *publish_base
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PYPI_TOKEN
  script:
    - twine upload dist/*
  only:
    - tags
