name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  push-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log In
        run: echo "Docker Login"

      - name: Build & Push the Server
        run: make server-push

  push-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log In
        run: echo "Docker Login"

      - name: Build & Push the CLI
        run: make cli-push
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material Pygments
      - run: mkdocs gh-deploy --force
