name: Docker Build & Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ethycaci
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  push-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log In
        run: make docker-login

      - name: Build & Push the Server
        run: make server-push

  push-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log In
        run: make docker-login

      - name: Build & Push the CLI
        run: make cli-push
